version: 2
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "./app/package.json" }}
      - run: 
        command: npm install
        working_directory: app
      - save_cache:
          paths:
            - node_modules
          key: npm-{{ checksum "./app/package.json" }}
      - run:
        command: npm run lint
        working_directory: app
      - run:
        command: npm run test
        working_directory: app
  deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "./app/package.json" }}
      - run:
        command: npm install
        working_directory: app
      - run:
        command: git config user.name $GITHUB_NAME
        working_directory: app
      - run:
        command: git config user.email $GITHUB_EMAIL
        working_directory: app
      - run:
        command: npm run generate:gh-pages
        working_directory: app
      - run:
        command: npm run deploy:gh-pages
        working_directory: app
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
